### ISSUE TITLE
Authentication conflict when signing in to Teams with a managed account and then signing in with a separate non-managed account

### ISSUE THREAD

**Issue by ClaudioConsolmagno** [microsoft/botbuilder-java#1471] opened 2022-06-06 12:12 UTC
## Version
- Bot dependency versions
   ```groovy
   implementation 'com.microsoft.bot:bot-integration-spring:4.14.2'
   implementation 'com.microsoft.bot:bot-dialogs:4.14.2'
   ```
- Windows 10
- Microsoft Teams Version 1.5.00.12969 (64-bit)

## Describe the bug
I'm having issues with Teams authentication using the incorrect account with my bot. That happens when I have an account that is "Managed" and then try to authenticate with the bot with a separate "unmanaged" account. If you have Account A which is managed and Account B which is not managed, when you login to the bot with Account B it uses the credentials of Account A instead. I can see the SSO window pops up quickly and closes down right away so I guess the SSO window sees that I have a _single_ signed in managed account so it just uses it for convenience but it doesn't check that it was the same account that triggered the authentication in the first place so the wrong account is used.

## To Reproduce
1. I sign in to Teams with an account A and use "Allow my organisation to manage my device" in order to stay signed in. I can _only_ see this account if I go to Windows Settings > Accounts > Access work or school.
2. Once I'm signed in with account A, I navigate into my app and attempt to sign in with my bot. Given SSO, a window pops open and closes right away. The sign in is successful.
3. I then sign out from Teams (app is closed and re-opened) and sign in with another account (B) but for that account I use "No, sign in to this app only" option so that I don't stay signed in (i.e. account is unmanaged). I do NOT see this account if I go to Windows Settings > Accounts > Access work or school (I only see Account A).
4. Once I'm signed in with account B, I navigate into my app and attempt to sign in with my bot. Similar to step 2 above, a window pops open and closes right away. The sign in is successful BUT on my bot I can see that it was account A that was signed in and not account B.

## Expected behavior
On step 4 above either one of these 2 options:
- When the sign in attempt is triggered, the window pops open and stays open so that I can select which account I'd like to login.
- When the sign in attempt is triggered, the current logged in account (account B) is used for SSO and not any other accounts.

## Additional context
My bot has been implemented in a similar way as it's described in the bot samples repo ([46.teams-auth](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/java_springboot/46.teams-auth)). There is no way as far as I know to force that the account that triggered the sign in (in the `promptStep()`) to be the same as the one that is returned in the `loginStep()`.

**Comment by anishprasad01** [comment] 2022-06-06 21:50
Hi @ClaudioConsolmagno,

Thanks for the report. I was able to reproduce this behavior. At this point, I'm going to look into it further and see if this is a Bot Framework SDK issue, a Teams issue, or expected behavior. Then we can figure out next steps.

**Comment by anishprasad01** [comment] 2022-06-07 18:43
It looks like this is expected behavior. 

If we think about what SSO stands for, Single-Sign On, it makes sense that you would not be prompted to sign-in again. SSO by definition looks to see if you have a profile that fulfils the requirements (your managed account) and automatically signs it in, thus simplifying the process for the end user. The pop-up window that's getting skipped is only a first-time authorization to allow access your profile, as opposed to a proper login prompt. Once you allow it, it is expected that the prompt should not reappear for the same application, no matter how many times you log out and in again.

Furthermore, the Bot Framework SDK does not handle any of the auth code itself, it calls external libraries to handle authentication. The auth flow is checking your machine and pulling your credentials. The bot doesn't know how to do that, and so you cannot force the behavior you're looking for from the bot. The bot does not handle authentication, it is only given access by the result of the auth flow. I can also confirm that the other versions of the Bot SDK also operate the same way by design.

If you still want a prompt, you will have to use an alternate sign in method that does not make use of SSO. Perhaps the Teams support side would be able to help you with that.

Since this is expected behavior, I am going to close this issue. If you have issues or feature requests in the future, please feel free to raise them in the appropriate repository.

**Closed by anishprasad01** 2022-06-07 18:43 UTC
Labels: bug, customer-reported, customer-replied-to, Bot Services

**Comment by ClaudioConsolmagno** [comment] 2022-06-09 09:33
This is totally unexpected behaviour. The user logs in to Teams with an account and if they try to login to a bot they would expect that same account to be used and not any other accounts (unless they are able to explicitly choose a separate account).

I understand that it may not be something that can be fixed with the SDK but we can't fix that in the bot code either. The only thing I can do is to change the "login successful" message to something like "login successful with $email" and let the user figure out whether that's the right account or not. Not sure Teams App reviewers would be happy with this approach though. There's no way to know from the bot code what email the user has used to login to Teams and make sure that matches what was authenticated with the bot (technically you _could_  but that's deprecated functionality being removed later this year ([link 1](https://github.com/microsoft/botbuilder-java/issues/1457), [link 2](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/team-chat-member-api-changes)).

I'll try and raise this with the MS community forums but if there's a directly Teams technical help page let me know and I'll use that instead.

**Comment by anishprasad01** [comment] 2022-06-09 15:10
I understand the confusion (I thought the same at first), and hopefully the Teams side can clear it up. Here's the list of Teams dev [support resources](https://docs.microsoft.com/enus/microsoftteams/platform/feedback?wt.mc_id=devcomteams_navcommunity_webpage_mw). In addition to posting on the community, you can try asking on StackOverflow with the `microsoft-teams` tag. There are often Teams reps who check tagged posts and they might be able to offer a quick answer.
