### ISSUE TITLE
401 Issues 

### ISSUE THREAD

**Issue by DanielFedorowsky** [Microsoft/botbuilder-java#55] opened 2018-08-02 07:13 UTC
Hello,

I have a bot in MS Teams that I communicate with using this library.
Recently, we noticed that after the bot is up for a few days we suddenly keep getting 401 when we try to send a message. Even though JwtTokenValidation.assertValidActivity doesn't throw any exception.
The problem only disappears after we restart our servers.

This is the 401 exception we get:

```
com.microsoft.bot.connector.models.ErrorResponseException: Status code 401, {"message":"Authorization has been denied for this request."}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
	at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
	at com.microsoft.bot.connector.implementation.ConversationsImpl.sendToConversationDelegate(ConversationsImpl.java:510)
```

We are using the 4.0.0-a1 version.
Thanks

**Comment by DanielFedo** [comment] 2018-08-16 09:06
I have found and fixed the root cause of this issue.
[Create a pull request](https://github.com/Microsoft/botbuilder-java/pull/56) for the fix.

**Comment by daveta** [comment] 2018-09-22 20:43
Awesome - thanks Daniel.  This has been merged, closing issue.

**Closed by daveta** 2018-09-22 20:43 UTC

**Comment by andrepra** [comment] 2019-09-16 15:12
We are getting the same exception (4.0.0-a1). Could you tell me which version fix this issue? tnx

**Comment by tracyboehrer** [comment] 2019-09-16 15:30
@andrepra I don't believe another preview was released after the merge for this issue.  However, we are getting close to releasing a Preview 2 which would have a number of fixes and enhancements to bring it closer to the other platforms.

**Comment by andrepra** [comment] 2019-09-16 16:14
@tracyboehrer thanks for your answer. Do you know if exists any workaround we can do on our code to avoid the exception?
